# Generated by Django 6.0.3 on 2026-04-13 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_block_users", "Может блокировать пользователей")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_view_all_recipients", "Может просматривать всех получателей"),
                    ("can_block_recipients", "Может блокировать получателей"),
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
