# Generated by Django 6.0.3 on 2026-04-09 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_all_recipients", "Может просматривать всех получателей"),
                    ("can_block_recipients", "Может блокировать получателей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
