# Generated by Django 6.0.3 on 2026-04-13 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_block_users", "Может блокировать пользователей")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
