# Generated by Django 6.0.3 on 2026-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_attempttosend"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempttosend",
            name="server_response",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
