# Generated by Django 6.0.3 on 2026-04-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0005_mailingmodel_created_at_mailingmodel_updated_at_and_more"),
        ("users", "0005_recipient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingmodel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="recipients",
            field=models.ManyToManyField(to="users.recipient"),
        ),
    ]
