# Generated by Django 6.0.3 on 2026-04-09 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0006_mailingmodel_owner_alter_mailingmodel_recipients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingmodel",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="messagemodel",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения"),
                    ("can_disable_message", "Может отключать сообщения"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
