# Generated by Django 6.0.3 on 2026-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0008_messagemodel_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("disables", "Отключена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
